/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const APIException = require('./APIException');
/**
 * Creates an instance of VincularClienteTags412ResponseException
 */
class VincularClienteTags412ResponseException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * TODO: Write general description for this field
         */
        this.mensagem = null;

        /**
         * TODO: Write general description for this field
         */
        this.erros = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'mensagem', realName: 'mensagem' },
            { name: 'erros', realName: 'erros', array: true, type: 'Erro' },
        ]);
    }
}

module.exports = VincularClienteTags412ResponseException;
