/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of AjustarOEstoqueDeProdutoRequest
 */
class AjustarOEstoqueDeProdutoRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.produtoId = this.constructor.getValue(obj.produtoId || obj.produto_id);
        this.novoSaldo = this.constructor.getValue(obj.novoSaldo || obj.novo_saldo);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'produtoId', realName: 'produto_id' },
            { name: 'novoSaldo', realName: 'novo_saldo' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = AjustarOEstoqueDeProdutoRequest;
