/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of AlterarUmProdutoResponse
 */
class AlterarUmProdutoResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.nome = this.constructor.getValue(obj.nome);
        this.precoTabela = this.constructor.getValue(obj.precoTabela || obj.preco_tabela);
        this.precoMinimo = this.constructor.getValue(obj.precoMinimo || obj.preco_minimo);
        this.codigo = this.constructor.getValue(obj.codigo);
        this.comissao = this.constructor.getValue(obj.comissao);
        this.ipi = this.constructor.getValue(obj.ipi);
        this.tipoIpi = this.constructor.getValue(obj.tipoIpi || obj.tipo_ipi);
        this.st = this.constructor.getValue(obj.st);
        this.moeda = this.constructor.getValue(obj.moeda);
        this.unidade = this.constructor.getValue(obj.unidade);
        this.saldoEstoque = this.constructor.getValue(obj.saldoEstoque || obj.saldo_estoque);
        this.observacoes = this.constructor.getValue(obj.observacoes);
        this.gradeCores = this.constructor.getValue(obj.gradeCores || obj.grade_cores);
        this.gradeTamanhos = this.constructor.getValue(obj.gradeTamanhos || obj.grade_tamanhos);
        this.excluido = this.constructor.getValue(obj.excluido);
        this.ativo = this.constructor.getValue(obj.ativo);
        this.categoriaId = this.constructor.getValue(obj.categoriaId || obj.categoria_id);
        this.codigoNcm = this.constructor.getValue(obj.codigoNcm || obj.codigo_ncm);
        this.multiplo = this.constructor.getValue(obj.multiplo);
        this.pesoBruto = this.constructor.getValue(obj.pesoBruto || obj.peso_bruto);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'nome', realName: 'nome' },
            { name: 'precoTabela', realName: 'preco_tabela' },
            { name: 'precoMinimo', realName: 'preco_minimo' },
            { name: 'codigo', realName: 'codigo' },
            { name: 'comissao', realName: 'comissao' },
            { name: 'ipi', realName: 'ipi' },
            { name: 'tipoIpi', realName: 'tipo_ipi' },
            { name: 'st', realName: 'st' },
            { name: 'moeda', realName: 'moeda' },
            { name: 'unidade', realName: 'unidade' },
            { name: 'saldoEstoque', realName: 'saldo_estoque' },
            { name: 'observacoes', realName: 'observacoes' },
            { name: 'gradeCores', realName: 'grade_cores', array: true },
            { name: 'gradeTamanhos', realName: 'grade_tamanhos' },
            { name: 'excluido', realName: 'excluido' },
            { name: 'ativo', realName: 'ativo' },
            { name: 'categoriaId', realName: 'categoria_id' },
            { name: 'codigoNcm', realName: 'codigo_ncm' },
            { name: 'multiplo', realName: 'multiplo' },
            { name: 'pesoBruto', realName: 'peso_bruto' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = AlterarUmProdutoResponse;
