/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of AlterarFaturamentoDoPedidoRequest
 */
class AlterarFaturamentoDoPedidoRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.pedidoId = this.constructor.getValue(obj.pedidoId || obj.pedido_id);
        this.valorFaturado = this.constructor.getValue(obj.valorFaturado || obj.valor_faturado);
        this.dataFaturamento =
          this.constructor.getValue(obj.dataFaturamento
     || obj.data_faturamento);
        this.numeroNf = this.constructor.getValue(obj.numeroNf || obj.numero_nf);
        this.informacoesAdicionais =
          this.constructor.getValue(obj.informacoesAdicionais
     || obj.informacoes_adicionais);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'pedidoId', realName: 'pedido_id' },
            { name: 'valorFaturado', realName: 'valor_faturado' },
            { name: 'dataFaturamento', realName: 'data_faturamento' },
            { name: 'numeroNf', realName: 'numero_nf' },
            { name: 'informacoesAdicionais', realName: 'informacoes_adicionais' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = AlterarFaturamentoDoPedidoRequest;
