/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of AlterarUmTTuloRequest
 */
class AlterarUmTTuloRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.clienteId = this.constructor.getValue(obj.clienteId || obj.cliente_id);
        this.numeroDocumento =
          this.constructor.getValue(obj.numeroDocumento
     || obj.numero_documento);
        this.dataVencimento = this.constructor.getValue(obj.dataVencimento || obj.data_vencimento);
        this.valor = this.constructor.getValue(obj.valor);
        this.observacao = this.constructor.getValue(obj.observacao);
        this.excluido = this.constructor.getValue(obj.excluido);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'clienteId', realName: 'cliente_id' },
            { name: 'numeroDocumento', realName: 'numero_documento' },
            { name: 'dataVencimento', realName: 'data_vencimento' },
            { name: 'valor', realName: 'valor' },
            { name: 'observacao', realName: 'observacao' },
            { name: 'excluido', realName: 'excluido' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = AlterarUmTTuloRequest;
