/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of AlterarUmPedidoRequest
 */
class AlterarUmPedidoRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.clienteId = this.constructor.getValue(obj.clienteId || obj.cliente_id);
        this.dataEmissao = this.constructor.getValue(obj.dataEmissao || obj.data_emissao);
        this.contatoId = this.constructor.getValue(obj.contatoId || obj.contato_id);
        this.transportadoraId =
          this.constructor.getValue(obj.transportadoraId
     || obj.transportadora_id);
        this.enderecoEntregaId =
          this.constructor.getValue(obj.enderecoEntregaId
     || obj.endereco_entrega_id);
        this.criadorId = this.constructor.getValue(obj.criadorId || obj.criador_id);
        this.condicaoPagamentoId =
          this.constructor.getValue(obj.condicaoPagamentoId
     || obj.condicao_pagamento_id);
        this.condicaoPagamento =
          this.constructor.getValue(obj.condicaoPagamento
     || obj.condicao_pagamento);
        this.tipoPedidoId = this.constructor.getValue(obj.tipoPedidoId || obj.tipo_pedido_id);
        this.formaPagamentoId =
          this.constructor.getValue(obj.formaPagamentoId
     || obj.forma_pagamento_id);
        this.observacoes = this.constructor.getValue(obj.observacoes);
        this.extras = this.constructor.getValue(obj.extras);
        this.itens = this.constructor.getValue(obj.itens);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'clienteId', realName: 'cliente_id' },
            { name: 'dataEmissao', realName: 'data_emissao' },
            { name: 'contatoId', realName: 'contato_id' },
            { name: 'transportadoraId', realName: 'transportadora_id' },
            { name: 'enderecoEntregaId', realName: 'endereco_entrega_id' },
            { name: 'criadorId', realName: 'criador_id' },
            { name: 'condicaoPagamentoId', realName: 'condicao_pagamento_id' },
            { name: 'condicaoPagamento', realName: 'condicao_pagamento' },
            { name: 'tipoPedidoId', realName: 'tipo_pedido_id' },
            { name: 'formaPagamentoId', realName: 'forma_pagamento_id' },
            { name: 'observacoes', realName: 'observacoes' },
            { name: 'extras', realName: 'extras', array: true, type: 'Extra2' },
            { name: 'itens', realName: 'itens', array: true, type: 'Iten1' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = AlterarUmPedidoRequest;
