/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Contato
 */
class Contato extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.nome = this.constructor.getValue(obj.nome);
        this.cargo = this.constructor.getValue(obj.cargo);
        this.emails = this.constructor.getValue(obj.emails);
        this.telefones = this.constructor.getValue(obj.telefones);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'nome', realName: 'nome' },
            { name: 'cargo', realName: 'cargo' },
            { name: 'emails', realName: 'emails', array: true, type: 'Email' },
            { name: 'telefones', realName: 'telefones', array: true, type: 'Telefone' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Contato;
