/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EnderecosAdicionai
 */
class EnderecosAdicionai extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.cep = this.constructor.getValue(obj.cep);
        this.endereco = this.constructor.getValue(obj.endereco);
        this.numero = this.constructor.getValue(obj.numero);
        this.complemento = this.constructor.getValue(obj.complemento);
        this.bairro = this.constructor.getValue(obj.bairro);
        this.cidade = this.constructor.getValue(obj.cidade);
        this.estado = this.constructor.getValue(obj.estado);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'cep', realName: 'cep' },
            { name: 'endereco', realName: 'endereco' },
            { name: 'numero', realName: 'numero' },
            { name: 'complemento', realName: 'complemento' },
            { name: 'bairro', realName: 'bairro' },
            { name: 'cidade', realName: 'cidade' },
            { name: 'estado', realName: 'estado' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = EnderecosAdicionai;
