/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of IncluirUmCampoExtraRequest
 */
class IncluirUmCampoExtraRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.tipo = this.constructor.getValue(obj.tipo);
        this.nome = this.constructor.getValue(obj.nome);
        this.obrigatorio = this.constructor.getValue(obj.obrigatorio);
        this.exibirParaCliente =
          this.constructor.getValue(obj.exibirParaCliente
     || obj.exibir_para_cliente);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'tipo', realName: 'tipo' },
            { name: 'nome', realName: 'nome' },
            { name: 'obrigatorio', realName: 'obrigatorio' },
            { name: 'exibirParaCliente', realName: 'exibir_para_cliente' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = IncluirUmCampoExtraRequest;
