/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of IncluirUmaConfiguraODeICMSSTRequest
 */
class IncluirUmaConfiguraODeICMSSTRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.codigoNcm = this.constructor.getValue(obj.codigoNcm || obj.codigo_ncm);
        this.icmsCredito = this.constructor.getValue(obj.icmsCredito || obj.icms_credito);
        this.estadoDestino = this.constructor.getValue(obj.estadoDestino || obj.estado_destino);
        this.nomeExcecaoFiscal =
          this.constructor.getValue(obj.nomeExcecaoFiscal
     || obj.nome_excecao_fiscal);
        this.valorMva = this.constructor.getValue(obj.valorMva || obj.valor_mva);
        this.valorPmc = this.constructor.getValue(obj.valorPmc || obj.valor_pmc);
        this.icmsDestino = this.constructor.getValue(obj.icmsDestino || obj.icms_destino);
        this.tipoSt = this.constructor.getValue(obj.tipoSt || obj.tipo_st);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'codigoNcm', realName: 'codigo_ncm' },
            { name: 'icmsCredito', realName: 'icms_credito' },
            { name: 'estadoDestino', realName: 'estado_destino' },
            { name: 'nomeExcecaoFiscal', realName: 'nome_excecao_fiscal' },
            { name: 'valorMva', realName: 'valor_mva' },
            { name: 'valorPmc', realName: 'valor_pmc' },
            { name: 'icmsDestino', realName: 'icms_destino' },
            { name: 'tipoSt', realName: 'tipo_st' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = IncluirUmaConfiguraODeICMSSTRequest;
