/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of IncluirUmaCondiODePagamentoRequest
 */
class IncluirUmaCondiODePagamentoRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.nome = this.constructor.getValue(obj.nome);
        this.valorMinimo = this.constructor.getValue(obj.valorMinimo || obj.valor_minimo);
        this.excluido = this.constructor.getValue(obj.excluido);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'nome', realName: 'nome' },
            { name: 'valorMinimo', realName: 'valor_minimo' },
            { name: 'excluido', realName: 'excluido' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = IncluirUmaCondiODePagamentoRequest;
