/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of IncluirUmClienteRequest
 */
class IncluirUmClienteRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.razaoSocial = this.constructor.getValue(obj.razaoSocial || obj.razao_social);
        this.nomeFantasia = this.constructor.getValue(obj.nomeFantasia || obj.nome_fantasia);
        this.tipo = this.constructor.getValue(obj.tipo);
        this.cnpj = this.constructor.getValue(obj.cnpj);
        this.inscricaoEstadual =
          this.constructor.getValue(obj.inscricaoEstadual
     || obj.inscricao_estadual);
        this.suframa = this.constructor.getValue(obj.suframa);
        this.rua = this.constructor.getValue(obj.rua);
        this.numero = this.constructor.getValue(obj.numero);
        this.complemento = this.constructor.getValue(obj.complemento);
        this.bairro = this.constructor.getValue(obj.bairro);
        this.cep = this.constructor.getValue(obj.cep);
        this.cidade = this.constructor.getValue(obj.cidade);
        this.estado = this.constructor.getValue(obj.estado);
        this.observacao = this.constructor.getValue(obj.observacao);
        this.emails = this.constructor.getValue(obj.emails);
        this.telefones = this.constructor.getValue(obj.telefones);
        this.contatos = this.constructor.getValue(obj.contatos);
        this.enderecosAdicionais =
          this.constructor.getValue(obj.enderecosAdicionais
     || obj.enderecos_adicionais);
        this.nomeExcecaoFiscal =
          this.constructor.getValue(obj.nomeExcecaoFiscal
     || obj.nome_excecao_fiscal);
        this.segmentoId = this.constructor.getValue(obj.segmentoId || obj.segmento_id);
        this.excluido = this.constructor.getValue(obj.excluido);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'razaoSocial', realName: 'razao_social' },
            { name: 'nomeFantasia', realName: 'nome_fantasia' },
            { name: 'tipo', realName: 'tipo' },
            { name: 'cnpj', realName: 'cnpj' },
            { name: 'inscricaoEstadual', realName: 'inscricao_estadual' },
            { name: 'suframa', realName: 'suframa' },
            { name: 'rua', realName: 'rua' },
            { name: 'numero', realName: 'numero' },
            { name: 'complemento', realName: 'complemento' },
            { name: 'bairro', realName: 'bairro' },
            { name: 'cep', realName: 'cep' },
            { name: 'cidade', realName: 'cidade' },
            { name: 'estado', realName: 'estado' },
            { name: 'observacao', realName: 'observacao' },
            { name: 'emails', realName: 'emails', array: true, type: 'Email' },
            { name: 'telefones', realName: 'telefones', array: true, type: 'Telefone' },
            { name: 'contatos', realName: 'contatos', array: true, type: 'Contato' },
            {
                name: 'enderecosAdicionais',
                realName: 'enderecos_adicionais',
                array: true,
                type: 'EnderecosAdicionai',
            },
            { name: 'nomeExcecaoFiscal', realName: 'nome_excecao_fiscal' },
            { name: 'segmentoId', realName: 'segmento_id' },
            { name: 'excluido', realName: 'excluido' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = IncluirUmClienteRequest;
