/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Iten9
 */
class Iten9 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.produtoId = this.constructor.getValue(obj.produtoId || obj.produto_id);
        this.tabelaPrecoId = this.constructor.getValue(obj.tabelaPrecoId || obj.tabela_preco_id);
        this.quantidadeGrades =
          this.constructor.getValue(obj.quantidadeGrades
     || obj.quantidade_grades);
        this.precoTabela = this.constructor.getValue(obj.precoTabela || obj.preco_tabela);
        this.descontosDoVendedor =
          this.constructor.getValue(obj.descontosDoVendedor
     || obj.descontos_do_vendedor);
        this.descontosDePromocoes =
          this.constructor.getValue(obj.descontosDePromocoes
     || obj.descontos_de_promocoes);
        this.descontosDePoliticas =
          this.constructor.getValue(obj.descontosDePoliticas
     || obj.descontos_de_politicas);
        this.moeda = this.constructor.getValue(obj.moeda);
        this.cotacaoMoeda = this.constructor.getValue(obj.cotacaoMoeda || obj.cotacao_moeda);
        this.observacoes = this.constructor.getValue(obj.observacoes);
        this.ipi = this.constructor.getValue(obj.ipi);
        this.tipoIpi = this.constructor.getValue(obj.tipoIpi || obj.tipo_ipi);
        this.st = this.constructor.getValue(obj.st);
        this.precoMinimo = this.constructor.getValue(obj.precoMinimo || obj.preco_minimo);
        this.excluido = this.constructor.getValue(obj.excluido);
        this.quantidade = this.constructor.getValue(obj.quantidade);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'produtoId', realName: 'produto_id' },
            { name: 'tabelaPrecoId', realName: 'tabela_preco_id' },
            {
                name: 'quantidadeGrades',
                realName: 'quantidade_grades',
                array: true,
                type: 'QuantidadeGrade',
            },
            { name: 'precoTabela', realName: 'preco_tabela' },
            { name: 'descontosDoVendedor', realName: 'descontos_do_vendedor', array: true },
            {
                name: 'descontosDePromocoes',
                realName: 'descontos_de_promocoes',
                array: true,
                type: 'DescontosDePromoco',
            },
            {
                name: 'descontosDePoliticas',
                realName: 'descontos_de_politicas',
                array: true,
                type: 'DescontosDePolitica',
            },
            { name: 'moeda', realName: 'moeda' },
            { name: 'cotacaoMoeda', realName: 'cotacao_moeda' },
            { name: 'observacoes', realName: 'observacoes' },
            { name: 'ipi', realName: 'ipi' },
            { name: 'tipoIpi', realName: 'tipo_ipi' },
            { name: 'st', realName: 'st' },
            { name: 'precoMinimo', realName: 'preco_minimo' },
            { name: 'excluido', realName: 'excluido' },
            { name: 'quantidade', realName: 'quantidade' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Iten9;
