/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ObterUmaTabelaDePreOResponse
 */
class ObterUmaTabelaDePreOResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.acrescimo = this.constructor.getValue(obj.acrescimo);
        this.tipo = this.constructor.getValue(obj.tipo);
        this.nome = this.constructor.getValue(obj.nome);
        this.ultimaAlteracao =
          this.constructor.getValue(obj.ultimaAlteracao
     || obj.ultima_alteracao);
        this.excluido = this.constructor.getValue(obj.excluido);
        this.id = this.constructor.getValue(obj.id);
        this.desconto = this.constructor.getValue(obj.desconto);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'acrescimo', realName: 'acrescimo' },
            { name: 'tipo', realName: 'tipo' },
            { name: 'nome', realName: 'nome' },
            { name: 'ultimaAlteracao', realName: 'ultima_alteracao' },
            { name: 'excluido', realName: 'excluido' },
            { name: 'id', realName: 'id' },
            { name: 'desconto', realName: 'desconto' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ObterUmaTabelaDePreOResponse;
