/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of VincularClienteCondiODePagamentoRequest
 */
class VincularClienteCondiODePagamentoRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.clienteId = this.constructor.getValue(obj.clienteId || obj.cliente_id);
        this.condicoesPagamentoLiberadas =
          this.constructor.getValue(obj.condicoesPagamentoLiberadas
     || obj.condicoes_pagamento_liberadas);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'clienteId', realName: 'cliente_id' },
            {
                name: 'condicoesPagamentoLiberadas',
                realName: 'condicoes_pagamento_liberadas',
                array: true,
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = VincularClienteCondiODePagamentoRequest;
