/**
 * APIDeIntegraOMercosLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ObterTodosOsProdutosResponse = require('../lib/Models/ObterTodosOsProdutosResponse');
const ObterUmProdutoEspecFicoResponse = require('../lib/Models/ObterUmProdutoEspecFicoResponse');
const IncluirUmProdutoRequest = require('../lib/Models/IncluirUmProdutoRequest');
const AlterarUmProdutoResponse = require('../lib/Models/AlterarUmProdutoResponse');
const AjustarOEstoqueDeProdutoRequest = require('../lib/Models/AjustarOEstoqueDeProdutoRequest');
const AjustarOEstoqueDeProdutoRequest1 = require('../lib/Models/AjustarOEstoqueDeProdutoRequest1');
const IncluirUmaImagemRequest = require('../lib/Models/IncluirUmaImagemRequest');
const IncluirUmaImagemRequest1 = require('../lib/Models/IncluirUmaImagemRequest1');
const Erro = require('../lib/Models/Erro');
const ObterTodasAsTabelasDePreOResponse =
  require('../lib/Models/ObterTodasAsTabelasDePreOResponse');
const ObterUmaTabelaDePreOResponse = require('../lib/Models/ObterUmaTabelaDePreOResponse');
const IncluirUmaTabelaDePreORequest = require('../lib/Models/IncluirUmaTabelaDePreORequest');
const AlterarUmaTabelaDePreORequest = require('../lib/Models/AlterarUmaTabelaDePreORequest');
const IncluirUmVNculoDeProdutoComTabelaDePreORequest =
  require('../lib/Models/IncluirUmVNculoDeProdutoComTabelaDePreORequest');
const AlterarUmVNculoDeProdutoComTabelaDePreORequest =
  require('../lib/Models/AlterarUmVNculoDeProdutoComTabelaDePreORequest');
const IncluirUmClienteRequest = require('../lib/Models/IncluirUmClienteRequest');
const Email = require('../lib/Models/Email');
const Telefone = require('../lib/Models/Telefone');
const Contato = require('../lib/Models/Contato');
const EnderecosAdicionai = require('../lib/Models/EnderecosAdicionai');
const AlterarUmClienteRequest = require('../lib/Models/AlterarUmClienteRequest');
const EnderecosAdicionai2 = require('../lib/Models/EnderecosAdicionai2');
const IncluirUmaNovaRedeRequest = require('../lib/Models/IncluirUmaNovaRedeRequest');
const AlterarUmaRedeExistenteRequest = require('../lib/Models/AlterarUmaRedeExistenteRequest');
const IncluirUmSegmentoRequest = require('../lib/Models/IncluirUmSegmentoRequest');
const AlterarUmSegmentoExistenteRequest =
  require('../lib/Models/AlterarUmSegmentoExistenteRequest');
const IncluirUmaTagRequest = require('../lib/Models/IncluirUmaTagRequest');
const AlterarUmaTagExistenteRequest = require('../lib/Models/AlterarUmaTagExistenteRequest');
const VincularClienteTagsRequest = require('../lib/Models/VincularClienteTagsRequest');
const IncluirUmaNovaCategoriaRequest = require('../lib/Models/IncluirUmaNovaCategoriaRequest');
const AlterarUmaCategoriaExistenteRequest =
  require('../lib/Models/AlterarUmaCategoriaExistenteRequest');
const VincularClienteCategoriaRequest = require('../lib/Models/VincularClienteCategoriaRequest');
const LiberarTodasAsCategoriasParaOClienteRequest =
  require('../lib/Models/LiberarTodasAsCategoriasParaOClienteRequest');
const VincularClienteTabelaDePreORequest =
  require('../lib/Models/VincularClienteTabelaDePreORequest');
const LiberarTodasAsTabelasDePreOParaOClienteRequest =
  require('../lib/Models/LiberarTodasAsTabelasDePreOParaOClienteRequest');
const IncluirUmaRegraDeLiberaORequest = require('../lib/Models/IncluirUmaRegraDeLiberaORequest');
const IncluirUmaTransportadoraRequest = require('../lib/Models/IncluirUmaTransportadoraRequest');
const AlterarUmaTransportadoraRequest = require('../lib/Models/AlterarUmaTransportadoraRequest');
const IncluirUmaCondiODePagamentoRequest =
  require('../lib/Models/IncluirUmaCondiODePagamentoRequest');
const AlterarUmaCondiODePagamentoRequest =
  require('../lib/Models/AlterarUmaCondiODePagamentoRequest');
const VincularClienteCondiODePagamentoRequest =
  require('../lib/Models/VincularClienteCondiODePagamentoRequest');
const LiberarTodasAsCondiEsDePagamentoParaOClienteRequest =
  require('../lib/Models/LiberarTodasAsCondiEsDePagamentoParaOClienteRequest');
const IncluirUmaFormaDePagamentoRequest =
  require('../lib/Models/IncluirUmaFormaDePagamentoRequest');
const AlterarUmaFormaDePagamentoRequest =
  require('../lib/Models/AlterarUmaFormaDePagamentoRequest');
const IncluirUmPedidoResponse = require('../lib/Models/IncluirUmPedidoResponse');
const Iten = require('../lib/Models/Iten');
const IncluirUmPedidoRequest = require('../lib/Models/IncluirUmPedidoRequest');
const Extra = require('../lib/Models/Extra');
const Iten1 = require('../lib/Models/Iten1');
const QuantidadeGrade = require('../lib/Models/QuantidadeGrade');
const AlterarUmPedidoRequest = require('../lib/Models/AlterarUmPedidoRequest');
const Extra2 = require('../lib/Models/Extra2');
const IncluirUmPedidoRequest2 = require('../lib/Models/IncluirUmPedidoRequest2');
const Iten6 = require('../lib/Models/Iten6');
const DescontosDePromoco = require('../lib/Models/DescontosDePromoco');
const DescontosDePolitica = require('../lib/Models/DescontosDePolitica');
const AlterarUmPedidoResponse = require('../lib/Models/AlterarUmPedidoResponse');
const AlterarUmPedidoRequest2 = require('../lib/Models/AlterarUmPedidoRequest2');
const Iten9 = require('../lib/Models/Iten9');
const CadastrarStatusRequest = require('../lib/Models/CadastrarStatusRequest');
const AlterarUmStatusRequest = require('../lib/Models/AlterarUmStatusRequest');
const AlterarStatusDeUmPedidoRequest = require('../lib/Models/AlterarStatusDeUmPedidoRequest');
const CadastrarTipoDePedidoRequest = require('../lib/Models/CadastrarTipoDePedidoRequest');
const AlterarUmTipoDePedidoRequest = require('../lib/Models/AlterarUmTipoDePedidoRequest');
const IncluirUmCampoExtraResponse = require('../lib/Models/IncluirUmCampoExtraResponse');
const IncluirUmCampoExtraRequest = require('../lib/Models/IncluirUmCampoExtraRequest');
const IncluirUmCampoExtraDoTipoListaResponse =
  require('../lib/Models/IncluirUmCampoExtraDoTipoListaResponse');
const AlterarUmCampoExtraResponse = require('../lib/Models/AlterarUmCampoExtraResponse');
const AlterarUmCampoExtraRequest = require('../lib/Models/AlterarUmCampoExtraRequest');
const AlterarUmCampoExtraDoTipoListaResponse =
  require('../lib/Models/AlterarUmCampoExtraDoTipoListaResponse');
const FaturarUmPedidoRequest = require('../lib/Models/FaturarUmPedidoRequest');
const AlterarFaturamentoDoPedidoRequest =
  require('../lib/Models/AlterarFaturamentoDoPedidoRequest');
const IncluirUmTTuloRequest = require('../lib/Models/IncluirUmTTuloRequest');
const AlterarUmTTuloRequest = require('../lib/Models/AlterarUmTTuloRequest');
const IncluirUmaConfiguraODeICMSSTRequest =
  require('../lib/Models/IncluirUmaConfiguraODeICMSSTRequest');
const AjustarOEstoqueDeProduto422ResponseException =
  require('../lib/Exceptions/AjustarOEstoqueDeProduto422ResponseException');
const IncluirUmaImagem412ResponseException =
  require('../lib/Exceptions/IncluirUmaImagem412ResponseException');
const IncluirUmVNculoDeProdutoComTabelaDePreO412ResponseException =
  require('../lib/Exceptions/IncluirUmVNculoDeProdutoComTabelaDePreO412ResponseException');
const AlterarUmVNculoDeProdutoComTabelaDePreO412ResponseException =
  require('../lib/Exceptions/AlterarUmVNculoDeProdutoComTabelaDePreO412ResponseException');
const IncluirUmCliente412ResponseException =
  require('../lib/Exceptions/IncluirUmCliente412ResponseException');
const AlterarUmCliente412ResponseException =
  require('../lib/Exceptions/AlterarUmCliente412ResponseException');
const IncluirUmaNovaRede412ResponseException =
  require('../lib/Exceptions/IncluirUmaNovaRede412ResponseException');
const AlterarUmaRedeExistente412ResponseException =
  require('../lib/Exceptions/AlterarUmaRedeExistente412ResponseException');
const IncluirUmSegmento412ResponseException =
  require('../lib/Exceptions/IncluirUmSegmento412ResponseException');
const AlterarUmSegmentoExistente412ResponseException =
  require('../lib/Exceptions/AlterarUmSegmentoExistente412ResponseException');
const IncluirUmaTag412ResponseException =
  require('../lib/Exceptions/IncluirUmaTag412ResponseException');
const AlterarUmaTagExistente412ResponseException =
  require('../lib/Exceptions/AlterarUmaTagExistente412ResponseException');
const VincularClienteTags412ResponseException =
  require('../lib/Exceptions/VincularClienteTags412ResponseException');
const IncluirUmaNovaCategoria412ResponseException =
  require('../lib/Exceptions/IncluirUmaNovaCategoria412ResponseException');
const AlterarUmaCategoriaExistente412ResponseException =
  require('../lib/Exceptions/AlterarUmaCategoriaExistente412ResponseException');
const VincularClienteCategoria412ResponseException =
  require('../lib/Exceptions/VincularClienteCategoria412ResponseException');
const LiberarTodasAsCategoriasParaOCliente412ResponseException =
  require('../lib/Exceptions/LiberarTodasAsCategoriasParaOCliente412ResponseException');
const VincularClienteTabelaDePreO412ResponseException =
  require('../lib/Exceptions/VincularClienteTabelaDePreO412ResponseException');
const LiberarTodasAsTabelasDePreOParaOCliente412ResponseException =
  require('../lib/Exceptions/LiberarTodasAsTabelasDePreOParaOCliente412ResponseException');
const IncluirUmaRegraDeLiberaO412ResponseException =
  require('../lib/Exceptions/IncluirUmaRegraDeLiberaO412ResponseException');
const IncluirUmaTransportadora412ResponseException =
  require('../lib/Exceptions/IncluirUmaTransportadora412ResponseException');
const AlterarUmaTransportadora412ResponseException =
  require('../lib/Exceptions/AlterarUmaTransportadora412ResponseException');
const IncluirUmaCondiODePagamento412ResponseException =
  require('../lib/Exceptions/IncluirUmaCondiODePagamento412ResponseException');
const AlterarUmaCondiODePagamento412ResponseException =
  require('../lib/Exceptions/AlterarUmaCondiODePagamento412ResponseException');
const VincularClienteCondiODePagamento412ResponseException =
  require('../lib/Exceptions/VincularClienteCondiODePagamento412ResponseException');
const LiberarTodasAsCondiEsDePagamentoParaOCliente412ResponseException =
  require('../lib/Exceptions/LiberarTodasAsCondiEsDePagamentoParaOCliente412ResponseException');
const IncluirUmaFormaDePagamento412ResponseException =
  require('../lib/Exceptions/IncluirUmaFormaDePagamento412ResponseException');
const AlterarUmaFormaDePagamento412ResponseException =
  require('../lib/Exceptions/AlterarUmaFormaDePagamento412ResponseException');
const IncluirUmPedido412ResponseException =
  require('../lib/Exceptions/IncluirUmPedido412ResponseException');
const AlterarUmPedido412ResponseException =
  require('../lib/Exceptions/AlterarUmPedido412ResponseException');
const IncluirUmPedido412Response1Exception =
  require('../lib/Exceptions/IncluirUmPedido412Response1Exception');
const AlterarUmPedido412Response1Exception =
  require('../lib/Exceptions/AlterarUmPedido412Response1Exception');
const CancelarUmPedido412ResponseException =
  require('../lib/Exceptions/CancelarUmPedido412ResponseException');
const CadastrarStatus412ResponseException =
  require('../lib/Exceptions/CadastrarStatus412ResponseException');
const AlterarUmStatus412ResponseException =
  require('../lib/Exceptions/AlterarUmStatus412ResponseException');
const AlterarStatusDeUmPedido412ResponseException =
  require('../lib/Exceptions/AlterarStatusDeUmPedido412ResponseException');
const CadastrarTipoDePedido412ResponseException =
  require('../lib/Exceptions/CadastrarTipoDePedido412ResponseException');
const AlterarUmTipoDePedido412ResponseException =
  require('../lib/Exceptions/AlterarUmTipoDePedido412ResponseException');
const IncluirUmCampoExtra412ResponseException =
  require('../lib/Exceptions/IncluirUmCampoExtra412ResponseException');
const IncluirUmCampoExtraDoTipoLista412ResponseException =
  require('../lib/Exceptions/IncluirUmCampoExtraDoTipoLista412ResponseException');
const AlterarUmCampoExtra412ResponseException =
  require('../lib/Exceptions/AlterarUmCampoExtra412ResponseException');
const AlterarUmCampoExtraDoTipoLista412ResponseException =
  require('../lib/Exceptions/AlterarUmCampoExtraDoTipoLista412ResponseException');
const FaturarUmPedido412ResponseException =
  require('../lib/Exceptions/FaturarUmPedido412ResponseException');
const AlterarFaturamentoDoPedido412ResponseException =
  require('../lib/Exceptions/AlterarFaturamentoDoPedido412ResponseException');
const IncluirUmTTulo412ResponseException =
  require('../lib/Exceptions/IncluirUmTTulo412ResponseException');
const AlterarUmTTulo412ResponseException =
  require('../lib/Exceptions/AlterarUmTTulo412ResponseException');

const classMap = {
    ObterTodosOsProdutosResponse,
    ObterUmProdutoEspecFicoResponse,
    IncluirUmProdutoRequest,
    AlterarUmProdutoResponse,
    AjustarOEstoqueDeProdutoRequest,
    AjustarOEstoqueDeProdutoRequest1,
    IncluirUmaImagemRequest,
    IncluirUmaImagemRequest1,
    Erro,
    ObterTodasAsTabelasDePreOResponse,
    ObterUmaTabelaDePreOResponse,
    IncluirUmaTabelaDePreORequest,
    AlterarUmaTabelaDePreORequest,
    IncluirUmVNculoDeProdutoComTabelaDePreORequest,
    AlterarUmVNculoDeProdutoComTabelaDePreORequest,
    IncluirUmClienteRequest,
    Email,
    Telefone,
    Contato,
    EnderecosAdicionai,
    AlterarUmClienteRequest,
    EnderecosAdicionai2,
    IncluirUmaNovaRedeRequest,
    AlterarUmaRedeExistenteRequest,
    IncluirUmSegmentoRequest,
    AlterarUmSegmentoExistenteRequest,
    IncluirUmaTagRequest,
    AlterarUmaTagExistenteRequest,
    VincularClienteTagsRequest,
    IncluirUmaNovaCategoriaRequest,
    AlterarUmaCategoriaExistenteRequest,
    VincularClienteCategoriaRequest,
    LiberarTodasAsCategoriasParaOClienteRequest,
    VincularClienteTabelaDePreORequest,
    LiberarTodasAsTabelasDePreOParaOClienteRequest,
    IncluirUmaRegraDeLiberaORequest,
    IncluirUmaTransportadoraRequest,
    AlterarUmaTransportadoraRequest,
    IncluirUmaCondiODePagamentoRequest,
    AlterarUmaCondiODePagamentoRequest,
    VincularClienteCondiODePagamentoRequest,
    LiberarTodasAsCondiEsDePagamentoParaOClienteRequest,
    IncluirUmaFormaDePagamentoRequest,
    AlterarUmaFormaDePagamentoRequest,
    IncluirUmPedidoResponse,
    Iten,
    IncluirUmPedidoRequest,
    Extra,
    Iten1,
    QuantidadeGrade,
    AlterarUmPedidoRequest,
    Extra2,
    IncluirUmPedidoRequest2,
    Iten6,
    DescontosDePromoco,
    DescontosDePolitica,
    AlterarUmPedidoResponse,
    AlterarUmPedidoRequest2,
    Iten9,
    CadastrarStatusRequest,
    AlterarUmStatusRequest,
    AlterarStatusDeUmPedidoRequest,
    CadastrarTipoDePedidoRequest,
    AlterarUmTipoDePedidoRequest,
    IncluirUmCampoExtraResponse,
    IncluirUmCampoExtraRequest,
    IncluirUmCampoExtraDoTipoListaResponse,
    AlterarUmCampoExtraResponse,
    AlterarUmCampoExtraRequest,
    AlterarUmCampoExtraDoTipoListaResponse,
    FaturarUmPedidoRequest,
    AlterarFaturamentoDoPedidoRequest,
    IncluirUmTTuloRequest,
    AlterarUmTTuloRequest,
    IncluirUmaConfiguraODeICMSSTRequest,
    AjustarOEstoqueDeProduto422ResponseException,
    IncluirUmaImagem412ResponseException,
    IncluirUmVNculoDeProdutoComTabelaDePreO412ResponseException,
    AlterarUmVNculoDeProdutoComTabelaDePreO412ResponseException,
    IncluirUmCliente412ResponseException,
    AlterarUmCliente412ResponseException,
    IncluirUmaNovaRede412ResponseException,
    AlterarUmaRedeExistente412ResponseException,
    IncluirUmSegmento412ResponseException,
    AlterarUmSegmentoExistente412ResponseException,
    IncluirUmaTag412ResponseException,
    AlterarUmaTagExistente412ResponseException,
    VincularClienteTags412ResponseException,
    IncluirUmaNovaCategoria412ResponseException,
    AlterarUmaCategoriaExistente412ResponseException,
    VincularClienteCategoria412ResponseException,
    LiberarTodasAsCategoriasParaOCliente412ResponseException,
    VincularClienteTabelaDePreO412ResponseException,
    LiberarTodasAsTabelasDePreOParaOCliente412ResponseException,
    IncluirUmaRegraDeLiberaO412ResponseException,
    IncluirUmaTransportadora412ResponseException,
    AlterarUmaTransportadora412ResponseException,
    IncluirUmaCondiODePagamento412ResponseException,
    AlterarUmaCondiODePagamento412ResponseException,
    VincularClienteCondiODePagamento412ResponseException,
    LiberarTodasAsCondiEsDePagamentoParaOCliente412ResponseException,
    IncluirUmaFormaDePagamento412ResponseException,
    AlterarUmaFormaDePagamento412ResponseException,
    IncluirUmPedido412ResponseException,
    AlterarUmPedido412ResponseException,
    IncluirUmPedido412Response1Exception,
    AlterarUmPedido412Response1Exception,
    CancelarUmPedido412ResponseException,
    CadastrarStatus412ResponseException,
    AlterarUmStatus412ResponseException,
    AlterarStatusDeUmPedido412ResponseException,
    CadastrarTipoDePedido412ResponseException,
    AlterarUmTipoDePedido412ResponseException,
    IncluirUmCampoExtra412ResponseException,
    IncluirUmCampoExtraDoTipoLista412ResponseException,
    AlterarUmCampoExtra412ResponseException,
    AlterarUmCampoExtraDoTipoLista412ResponseException,
    FaturarUmPedido412ResponseException,
    AlterarFaturamentoDoPedido412ResponseException,
    IncluirUmTTulo412ResponseException,
    AlterarUmTTulo412ResponseException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
